In [50]:
import pandas as pd
import numpy as np

In [51]:
# Open the wikipedia dataset
data = pd.read_csv('../data/glove.6B.50d.txt', sep=' ', header=None, quoting=csv.QUOTE_NONE, nrows=10000)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,50
0,the,0.418000,0.249680,-0.41242,0.12170,0.34527,-0.044457,-0.49688,-0.17862,-0.00066,...,-0.298710,-0.157490,-0.347580,-0.045637,-0.44251,0.187850,0.002785,-0.184110,-0.115140,-0.78581
1,",",0.013441,0.236820,-0.16899,0.40951,0.63812,0.477090,-0.42852,-0.55641,-0.36400,...,-0.080262,0.630030,0.321110,-0.467650,0.22786,0.360340,-0.378180,-0.566570,0.044691,0.30392
2,.,0.151640,0.301770,-0.16763,0.17684,0.31719,0.339730,-0.43478,-0.31086,-0.44999,...,-0.000064,0.068987,0.087939,-0.102850,-0.13931,0.223140,-0.080803,-0.356520,0.016413,0.10216
3,of,0.708530,0.570880,-0.47160,0.18048,0.54449,0.726030,0.18157,-0.52393,0.10381,...,-0.347270,0.284830,0.075693,-0.062178,-0.38988,0.229020,-0.216170,-0.225620,-0.093918,-0.80375
4,to,0.680470,-0.039263,0.30186,-0.17792,0.42962,0.032246,-0.41376,0.13228,-0.29847,...,-0.094375,0.018324,0.210480,-0.030880,-0.19722,0.082279,-0.094340,-0.073297,-0.064699,-0.26044

In [59]:
# Keep only the characters
mask_characters = data.iloc[:,0].str.match('^[a-zA-Z]')  # Bool mask of only characters
data_only_char = data[mask_characters]  # Apply mask on data
df_3000 = data_only_char.iloc[:3000]  # Select only 3000 first data points
df_3000.set_index(0, inplace=True)
df_3000.head()

,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
0,,,,,,,,,,,,,,,,,,,,,
the,0.41800,0.249680,-0.41242,0.121700,0.345270,-0.044457,-0.49688,-0.178620,-0.000660,-0.656600,...,-0.298710,-0.157490,-0.347580,-0.045637,-0.44251,0.187850,0.002785,-0.184110,-0.115140,-0.78581
of,0.70853,0.570880,-0.47160,0.180480,0.544490,0.726030,0.18157,-0.523930,0.103810,-0.175660,...,-0.347270,0.284830,0.075693,-0.062178,-0.38988,0.229020,-0.216170,-0.225620,-0.093918,-0.80375
to,0.68047,-0.039263,0.30186,-0.177920,0.429620,0.032246,-0.41376,0.132280,-0.298470,-0.085253,...,-0.094375,0.018324,0.210480,-0.030880,-0.19722,0.082279,-0.094340,-0.073297,-0.064699,-0.26044
and,0.26818,0.143460,-0.27877,0.016257,0.113840,0.699230,-0.51332,-0.473680,-0.330750,-0.138340,...,-0.069043,0.368850,0.251680,-0.245170,0.25381,0.136700,-0.311780,-0.632100,-0.250280,-0.38097
in,0.33042,0.249950,-0.60874,0.109230,0.036372,0.151000,-0.55083,-0.074239,-0.092307,-0.328210,...,-0.486090,-0.008027,0.031184,-0.365760,-0.42699,0.421640,-0.116660,-0.507030,-0.027273,-0.53285

In [77]:
# Do the same for bigger dimensions, and then save them

def clean(filename):
    data = pd.read_csv(filename, sep=' ', header=None, quoting=csv.QUOTE_NONE, nrows=10000)
    mask_characters = data.iloc[:,0].str.match('^[a-zA-Z]', na=False)  # Bool mask of only characters
    data_only_char = data[mask_characters]  # Apply mask on data
    df_3000 = data_only_char.iloc[:3000]  # Select only 3000 first data points
    df_3000.set_index(0, inplace=True)
    
    return df_3000

In [80]:
twitter = clean('../data/glove.twitter.27B.200d.txt')
print(twitter.shape)
twitter.head()

(3000, 200)

,1,2,3,4,5,6,7,8,9,10,...,191,192,193,194,195,196,197,198,199,200
0,,,,,,,,,,,,,,,,,,,,,
rt,0.556870,0.63284,-0.156090,0.263970,0.28015,-0.36506,-0.121280,0.452170,-0.161230,0.015791,...,-0.30669,-0.15438,-0.19857,0.064394,-0.14346,-0.10524,-0.572530,0.23857,-0.79235,0.237610
i,0.056404,0.49536,0.184390,0.054535,-0.51751,0.13517,-0.028431,-0.289410,-0.369370,0.138050,...,-0.47247,-0.23687,-0.10937,-0.234360,-0.75368,0.27098,-0.205150,0.63598,-0.18880,-0.035558
a,0.149310,0.27889,0.089979,0.408820,-0.21328,0.15406,-0.025642,-0.645150,-0.716430,-0.117940,...,0.12651,0.46811,0.49654,-0.186880,0.57106,-0.40908,-0.040246,-0.44821,0.31604,-0.493650
the,0.493500,0.35698,0.660680,-0.032975,0.24989,0.25936,-0.027169,0.068403,-0.290630,-0.457050,...,-0.16617,-0.17018,0.11233,0.160400,-0.17142,-0.15621,-0.113660,0.17706,-0.53695,-0.296990
you,0.196400,0.67153,0.006298,0.253590,-0.42097,0.38490,1.037800,-0.185360,-0.054244,-0.108560,...,-0.11518,0.55363,-0.18500,-0.196530,0.10566,-0.26214,0.203970,-0.30815,-0.12312,0.048926

In [81]:
crawler = clean('../data/glove.42B.300d.txt')
print(crawler.shape)
crawler.head()

(3000, 300)

,1,2,3,4,5,6,7,8,9,10,...,291,292,293,294,295,296,297,298,299,300
0,,,,,,,,,,,,,,,,,,,,,
the,-0.208380,-0.14932,-0.017528,-0.028432,-0.060104,-0.264600,-4.1445,0.62932,0.336720,-0.433950,...,-0.041244,-0.461820,0.027903,0.54657,-0.25894,0.395150,0.26144,-0.540660,0.211990,-0.009436
and,-0.096110,-0.25788,-0.358600,-0.328870,0.579500,-0.517740,-4.1582,-0.11371,-0.108480,-0.488850,...,0.477810,-0.021213,-0.212360,0.42374,0.14083,0.067498,-0.12675,-0.370300,-0.092774,0.390580
to,-0.248370,-0.45461,0.039227,-0.284220,-0.031852,0.263550,-4.6323,0.01389,-0.539280,-0.084454,...,0.082736,-0.624690,0.044267,0.60673,-0.12458,-0.154430,-0.16339,0.053097,0.154580,-0.380530
of,-0.036429,-0.28592,0.063387,-0.601220,-0.015309,0.073243,-3.8547,0.52809,-0.077859,-0.407560,...,-0.021308,-0.660190,0.090383,0.12859,0.22616,0.302350,-0.25703,-0.489260,0.305370,0.272730
a,-0.035835,0.77844,-0.518060,0.080682,-0.131730,-0.286060,-4.2485,0.81827,0.240340,-0.690570,...,0.084727,0.104590,-0.253590,-0.12002,-0.38965,-0.287800,0.00367,0.022321,-0.315910,-0.356080

In [82]:
wikipedia = clean('../data/glove.6B.300d.txt')
print(wikipedia.shape)
wikipedia.head()

(3000, 300)

,1,2,3,4,5,6,7,8,9,10,...,291,292,293,294,295,296,297,298,299,300
0,,,,,,,,,,,,,,,,,,,,,
the,0.046560,0.213180,-0.007436,-0.45854,-0.035639,0.236430,-0.288360,0.215210,-0.134860,-1.6413,...,-0.013064,-0.296860,-0.079913,0.195000,0.031549,0.285060,-0.087461,0.009061,-0.209890,0.053913
of,-0.076947,-0.021211,0.212710,-0.72232,-0.139880,-0.122340,-0.175210,0.121370,-0.070866,-1.5721,...,-0.366730,-0.386030,0.302900,0.015747,0.340360,0.478410,0.068617,0.183510,-0.291830,-0.046533
to,-0.257560,-0.057132,-0.671900,-0.38082,-0.364210,-0.082155,-0.010955,-0.082047,0.460560,-1.8477,...,-0.012806,-0.597070,0.317340,-0.252670,0.543840,0.063007,-0.049795,-0.160430,0.046744,-0.070621
and,0.038466,-0.039792,0.082747,-0.38923,-0.214310,0.170200,-0.025657,0.095780,0.238600,-1.6342,...,0.045194,-0.204050,-0.210970,-0.110250,0.021766,0.441290,0.327970,-0.334270,0.011807,0.059703
in,-0.443990,0.128170,-0.252470,-0.18582,-0.166140,0.259090,-0.226780,-0.069229,-0.077204,-1.5814,...,-0.274500,-0.037237,0.101040,0.107980,0.377270,0.879770,0.335830,-0.200430,-0.082191,-0.062550

In [83]:
wikipedia.to_csv('../data/wikipedia_3000.csv')
crawler.to_csv('../data/crawler_3000.csv')
twitter.to_csv('../data/twitter_3000.csv')